### ISSUE TITLE
Panic in strokeContour

### ISSUE THREAD

**Issue by lotodore** [andybalholm/stroke#3]
I'm using stroke with gioui, because the lines are a lot better than the "builtin" lines in gioui. Thanks for providing this extension!
I'm sorry I do not have a minimal case to reproduce this issue, but I keep getting panics in
https://github.com/andybalholm/stroke/blob/e592fb194b394b11b0670b871a21e60f6ef73c5e/stroke.go#L36

It seems that `len(outer)` can be 0 in some cases which leads to the panic. Any hint on how to fix this?

**Comment by lotodore** [comment]
This seems to happen if start point and end point of a line are the same. Is this not supported?

**Comment by andybalholm** [comment]
So is this happening when you're stroking a zero-length path? I can see how that would make a problem.

I think the fix would be to add a special case at line 32 to catch this situation (`if len(outer) == 0 || len(inner) == 0`). (I think inner and outer would be empty at the same times, but we might as well check both.) Then we need to decide what to do in that situation. The simplest thing would be `return nil, nil`. Then stroking a zero-length path would just return nothing. But it might also make sense to draw a square or a circle, depending on the current cap setting…

**Comment by lotodore** [comment]
Thanks for the quick reply. I've rechecked, yes, all cases where the panic occurs have zero-length paths. I think mathematically a line has zero width, so a line with zero length is probably a point(?), so drawing a point would be fine. Disclaimer: This is how I would need it to be, so naturally, I tend towards this solution. Other people may need the stroke code to simply do nothing.
I could work around this issue by adding 1 px if coordinates are the same, at the same time, others could skip drawing at all if coordinates are the same. It's kind of hard to decide :-).

It may decrease performance, if an additional check is added. But because slices include their length, no counting is done, so it's probably ok to add a check as you noted. Anyway, it would also be an option to specify (in the documentation) that zero length behaviour is undefined and not allowed to occur.

**Comment by andybalholm** [comment]
I don't think we need to worry about performance. This is Go, not C. So it already checks the length of the slice to give you a nice panic message instead of silently corrupting memory like C would. Repeating the check won't cost much time.

We should do something in the zero-length case. We just need to decide what, and implement it. Here is what SVG does:

> Any zero length subpath shall not be stroked if the [stroke-linecap](https://svgwg.org/specs/strokes/#StrokeLinecapProperty) property has a value of butt but shall be stroked if the [stroke-linecap](https://svgwg.org/specs/strokes/#StrokeLinecapProperty) property has a value of round or square, producing respectively a circle or a square centered at the given point.

**Comment by lotodore** [comment]
OK so I checked what default gioui behaviour is:

These are the "standard lines":
```
package main

import (
	"image/color"
	"os"

	"gioui.org/app"
	"gioui.org/f32"
	"gioui.org/io/system"
	"gioui.org/layout"
	"gioui.org/op"
	"gioui.org/op/clip"
	"gioui.org/op/paint"
	"gioui.org/unit"
)

func main() {
	go func() {
		mainWindow := app.NewWindow(
			app.Title("stroketest"),
			app.Size(unit.Dp(800), unit.Dp(600)),
		)
		var ops op.Ops

		for e := range mainWindow.Events() {
			switch e := e.(type) {
			case system.FrameEvent:
				gtx := layout.NewContext(&ops, e)

				bg := color.NRGBA{R: 0, G: 0, B: 0, A: 255}
				paint.Fill(gtx.Ops, bg)
				layout.Flex{
					Axis:    layout.Vertical,
					Spacing: layout.SpaceEnd,
				}.Layout(
					gtx,
					layout.Rigid(
						func(gtx layout.Context) layout.Dimensions {
							path := clip.Path{}
							path.Begin(gtx.Ops)
							path.MoveTo(f32.Pt(20, 20))
							path.LineTo(f32.Pt(300, 300))
							path.MoveTo(f32.Pt(20, 220))
							path.LineTo(f32.Pt(20, 220))
							stack := clip.Stroke{Path: path.End(), Width: 5}.Op().Push(gtx.Ops)
							paint.Fill(gtx.Ops, color.NRGBA{R: 255, G: 255, B: 255, A: 255})
							stack.Pop()
							return layout.Dimensions{Size: gtx.Constraints.Max}
						},
					),
				)
				e.Frame(gtx.Ops)
			}
		}
		os.Exit(0)
	}()
	app.Main()
}
```
This program does not panic and draws nothing (for the second line). So if x/stroke is supposed to be compatible, it should also probably not draw anything.
Is there any place available to store a setting/property, so that an alternative behaviour (non-default) would even be possible?

**Comment by andybalholm** [comment]
We could add a boolean to the Options struct, but my inclination is to just do return nil, nil and draw nothing like the gioui default.

**Comment by lotodore** [comment]
Thank you for the fix and for providing this library!
