### ISSUE TITLE
Suggestion: More options to select stroke cap

### ISSUE THREAD

**Issue by lotodore** [andybalholm/stroke#4]
I use this stroke library a lot with gioui and it is really a huge help for the project I'm working on.
In some cases I find myself wishing for some more flexibility when specifying the stroke cap. I'd have two suggestions (from daily use of this library):

1. The specified cap is used for both ends of the line, it would be great if different sides could have different caps. This can be simulated by drawing two overlapping lines, but ... no, better not
2. I'd really love to have a triangular cap as additional option :-) maybe this could be added?

Anyway, thank you very much for providing this library. The project I'm working on, which is drawing a lot of lines (some kind of plotting software), will soon be published with an open source license.

**Comment by andybalholm** [comment]
I'm open to pull requests.

The triangular cap should be simple to add.

Having different caps for beginning and ending should be fairly simple to implement, but I'm not sure how to do it without messing up the API for the normal case of both caps being the same.

**Comment by lotodore** [comment]
I've added a pull request to enable triangular cap.
Regarding different caps:
```
// Stroke defines a stroke.
type Stroke struct {
	Path  Path
	Width float32 // Width of the stroked path.

	// Miter is the limit to apply to a miter joint.
	Miter float32
	Cap   StrokeCap  // Cap describes the head of a stroked path.
	Cap2   StrokeCap  // Cap2 describes the tail of a stroked path.
	Join  StrokeJoin // Join describes how stroked paths are collated.

	Dashes Dashes
}
```
and Cap2 has a default value of "SameCap" or something like this? Just a thought.

**Comment by andybalholm** [comment]
That would require renumbering the options (because SameCap would need to be 0). And then Cap would default to SameCap too. What would that mean?

Maybe:

```go
    DifferentCaps bool
    EndCap        CapStyle
```

**Comment by lotodore** [comment]
You are right, the name `SameCap` would not work very well, but `DefaultCap` with same semantics as before could work.
DefaultCap for Cap means current default
DefaultCap for EndCap means same as Cap
I think that this would also be intuitive to use, however, I agree that your proposed two-variable solution is a bit more clear. Also, I just noted that default is different in stroke and gio-x, so using "DefaultCap" might cause confusion then.

I'm just slightly worried about adding two variables to each stroke for a feature that will only occasionally be used, so I would hope one variable would be enough.
Other alternative solutions like bitmask for Cap would also work, would you be open to that?

If the additional memory requirements are fine, I could also try to create a pull request with `DifferentCaps` and `EndCap`.

**Comment by andybalholm** [comment]
I'm not worried about the memory requirement.
I'm more worried about the cognitive load on people who need to think about this feature even though they will never use it.

**Comment by lotodore** [comment]
I thought about this - I'm not happy with this solution. As you are writing, most people won't need this, and even I would be using it for <0.1% of all lines drawn. I think we can keep this in mind, feel free to tag me if someone else also requests different caps. I will use the workaround to draw two lines in the few cases I'm using it for.
I will create a pull request for gio-x for the triangular caps, and once this is done, close this issue.
Thanks for considering the feature!

**Comment by lotodore** [comment]
I have created https://github.com/gioui/gio-x/pull/12 so I'm closing this issue. Thanks!
